#define SERIALDEBUG_SOFT_TX_BIT 6
#define SERIALDEBUG_SOFT_TX_DDR DDRA
#define SERIALDEBUG_SOFT_TX_PORT PORTA
#define SERIALDEBUG_BAUD 9600
#define SERIALDEBUG_STOP_BITS 1
#define SERIALDEBUG_MICROSECONDS_OVERHEAD_ADJUST 0
#define SERIALDEBUG_MICROSECONDS_PER_BIT ((1000000ul / SERIALDEBUG_BAUD) - SERIALDEBUG_MICROSECONDS_OVERHEAD_ADJUST)
#define SERLAILDEBUG_USE_INTRS 1
